version: '3.5'

services:
  prestashop:
    container_name: prestashop
    build:
      context: ./docker/prestashop
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./src/modules:/var/www/html/modules
      - ./src/themes:/var/www/html/themes
      - ./src/override:/var/www/html/override
    environment:
      PS_DEV_MODE: 1
      DB_SERVER: mysql
      DB_USER: devtest
      DB_PASSWD: devtest123
      DB_NAME: prestashop
      PS_INSTALL_AUTO: 0
    restart: on-failure
  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: devtest
      MYSQL_PASSWORD: devtest123
    restart: on-failure